dist: trusty
sudo: false
notifications:
  email: false
env:
- RELEASE_TAG="release-$TRAVIS_BUILD_NUMBER"
if: tag IS blank

jobs:
  include:
  - stage: build and publish
    language: java
    jdk: oraclejdk8
    install: skip
    before_script:
    - pwd
    - chmod a+x gradlew
    script: ./gradlew clean build -x test
    before_deploy:
    - git config --local user.name "Build Bot"
    - git config --local user.email "buildbot@example.com"
    - git tag -f $RELEASE_TAG
    deploy:
      provider: releases
      api_key: $GITHUB_OAUTH_TOKEN
      file: "build/libs/movie-fun-1.0-SNAPSHOT.war"
      skip_cleanup: true
  - stage: deploy to review
    language: java
    script:
    - echo "Downloading $RELEASE_TAG"
    - wget -P build/libs https://github.com/$GITHUB_USERNAME/mediabase/releases/download/$RELEASE_TAG/movie-fun-1.0-SNAPSHOT.war
    before_deploy:
    - echo "Deploying $RELEASE_TAG to review"
    deploy:
      provider: cloudfoundry
      api: $CF_API_URL
      username: $CF_USERNAME
      password: $CF_PASSWORD
      organization: $CF_ORG
      space: review
